services:
  lumenmon-client:
    build: .
    container_name: lumenmon-client
    pid: host
    network_mode: host
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - SERVER_URL=${SERVER_URL:-http://localhost:8080}  # Direct mode URL
      - SSH_SERVER=${SSH_SERVER:-localhost}              # SSH server host for tunnel mode
      - SSH_PORT=${SSH_PORT:-2222}                       # SSH server port
      - TRANSPORT=${TRANSPORT:-tunnel}                   # Transport mode: tunnel or direct
      - DEBUG=${DEBUG:-1}                                # Debug mode
    ports:
      - "9090:9090"             # Webhook forwarder
      - "2525:2525"             # SMTP forwarder
    volumes:
      - ./collectors:/collectors:ro  # Mount collectors as read-only for easy development
      - ./forwarders:/forwarders:ro  # Mount forwarders as read-only
