version: '3.8'

services:
  client:
    build: .
    volumes:
      - ssh-keys:/shared:ro
    networks:
      - lumenmon
    environment:
      - SERVER_HOST=lumenmon-server
      - SERVER_PORT=22
      - SERVER_USER=collector
      - SAMPLE_HZ=10
    command: |
      sh -c "
        echo '[client] Waiting for SSH keys...'
        while [ ! -f /shared/client_key ]; do sleep 1; done
        cp /shared/client_key /home/metrics/.ssh/id_rsa
        chmod 600 /home/metrics/.ssh/id_rsa
        exec /usr/local/bin/collect.sh
      "

networks:
  lumenmon:
    name: lumenmon-net
    external: true

volumes:
  ssh-keys:
    name: lumenmon-ssh-keys
    external: true