version: 2
updates:
  # Docker dependencies for console
  - package-ecosystem: "docker"
    directory: "/console"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"

  # Docker dependencies for agent
  - package-ecosystem: "docker"
    directory: "/agent"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"