#!/bin/bash
# Show lumenmon logs

case "${1:-console}" in
    console)
        docker logs -f lumenmon-console
        ;;
    agent)
        docker logs -f lumenmon-agent
        ;;
    *)
        echo "Usage: ./logs [console|agent]"
        exit 1
        ;;
esac