services:
  lumenmon-tui:
    build: .
    container_name: lumenmon-tui
    volumes:
      # Mount the server's database directory (remove read-only for SQLite access)
      - ../server/data:/app/data
      # Mount scripts for live development
      - ./scripts:/app/scripts:ro
      # Mount CSS file for ttyd
      - ./ttyd.css:/app/ttyd.css:ro
    ports:
      - "7681:7681"  # ttyd web terminal port
    environment:
      # Database settings
      - DB_PATH=/app/data/lumenmon.db
      
      # TUI settings
      - REFRESH_RATE=${REFRESH_RATE:-5}
      - AUTO_REFRESH=${AUTO_REFRESH:-true}
      - TERM=xterm-256color
      
      # Mode selection (web/direct)
      - TUI_MODE=${TUI_MODE:-web}
      
      # ttyd settings
      - TTYD_PORT=${TTYD_PORT:-7681}
      - TTYD_AUTH=${TTYD_AUTH:-}  # Optional: username:password
      - TTYD_MAX_CLIENTS=${TTYD_MAX_CLIENTS:-10}
      - TTYD_READONLY=${TTYD_READONLY:-false}
      - TTYD_SSL=${TTYD_SSL:-false}
      - TTYD_TITLE=Lumenmon TUI
    
    restart: unless-stopped