services:
  server:
    build: ./server
    ports:
      - "8080:8080"
    environment:
      PORT: "8080"
      GREETING: "Hello from v2/connect server"
  client:
    build: ./client
    depends_on:
      - server
    environment:
      SERVER_HOST: server
      SERVER_PORT: "8080"
