services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: connect-server
    ports:
      - "2222:22"
    stdin_open: true
    tty: true
networks:
  default:
    name: connect-net
