[theme]
# HOT 80s CYBERPUNK NEON THEME
base = "dark"

# Neon color palette - hot pink/cyan/purple
primaryColor = "#ff00ff"              # Hot magenta/pink for interactive elements
textColor = "#00ffff"                 # Cyan text for that TRON feel
backgroundColor = "#000000"           # Deep black background
secondaryBackgroundColor = "#1a001a"  # Dark purple tint for containers

# Font configuration
font = "monospace"                    # Retro terminal font

[server]
# Performance and behavior settings
headless = true                       # Run without opening browser
enableCORS = false                    # Security setting
enableXsrfProtection = false          # Security setting  
maxUploadSize = 10                    # Max upload in MB
enableWebsocketCompression = true     # Better performance

[browser]
# Disable telemetry
gatherUsageStats = false             # Privacy setting

[runner]
# Magic commands and error handling
magicEnabled = false                  # Disable magic commands

[client]
# Client-side behavior
showErrorDetails = true               # Show full errors
toolbarMode = "minimal"               # Minimal toolbar